# URL (servletPath) = Action class
/user/search.do=com.example.app.action.UserSearchAction
/user/safeSearch.do=com.example.app.action.SafeUserSearchAction
/file/download.do=com.example.app.action.FileDownloadAction
/echo.do=com.example.app.action.EchoAction
